"""Caddy configuration and owned-process helpers."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import ipaddress
import re


MAX_API_REQUEST_BODY_SIZE = "110MB"


@dataclass(frozen=True)
class GatewayConfig:
    bind_ip: str
    port: int
    domain: str
    backend_port: int
    frontend_root: Path
    log_path: Path
    https: bool = False


def _caddy_path(path: Path) -> str:
    return path.resolve().as_posix()


def render_caddyfile(config: GatewayConfig) -> str:
    ipaddress.ip_address(config.bind_ip)
    if not re.fullmatch(r"[a-z0-9][a-z0-9.-]*\.local", config.domain):
        raise ValueError("Invalid LAN domain.")
    if not (config.frontend_root / "index.html").is_file():
        raise ValueError("Frontend production index.html is missing.")
    scheme = "https" if config.https else "http"
    auto_https = "" if config.https else "    auto_https off\n"
    tls = "\n    tls internal" if config.https else ""
    hsts = (
        '\n        Strict-Transport-Security "max-age=31536000"'
        if config.https
        else ""
    )
    return f"""# Generated by CIAL LAN manager. Do not edit.
{{
    admin 127.0.0.1:0
{auto_https.rstrip()}
}}

{scheme}://:{config.port} {{
    bind {config.bind_ip}{tls}

    @allowed_host host {config.domain} {config.bind_ip}
    handle @allowed_host {{
        header {{
            X-Content-Type-Options "nosniff"
            Referrer-Policy "no-referrer"
            Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=(), usb=()"
            X-Frame-Options "SAMEORIGIN"
            Content-Security-Policy "default-src 'self'; base-uri 'self'; frame-ancestors 'self'; object-src 'none'; img-src 'self' data: blob:; font-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'; worker-src 'self' blob:; connect-src 'self'; media-src 'self' blob:"{hsts}
            -Server
        }}

        @api path /api/*
        handle @api {{
            request_body {{
                max_size {MAX_API_REQUEST_BODY_SIZE}
            }}
            reverse_proxy 127.0.0.1:{config.backend_port} {{
                flush_interval -1
                header_up X-Forwarded-For {{remote_host}}
                header_up X-Forwarded-Host {{host}}
                header_up X-Forwarded-Proto {scheme}
                header_up -X-CIAL-User-Id
                header_up -X-User-Id
                header_up -X-CIAL-Access-Scope
            }}
        }}

        handle {{
            root * "{_caddy_path(config.frontend_root)}"
            @immutable path /assets/*
            header @immutable Cache-Control "public, max-age=31536000, immutable"
            try_files {{path}} /index.html
            file_server
        }}
    }}
    respond "Unexpected Host" 421

    handle_errors {{
        @backend_unavailable expression {{http.error.status_code}} == 502 || {{http.error.status_code}} == 503
        respond @backend_unavailable "<!doctype html><title>CIAL temporarily unavailable</title><h1>CIAL is starting</h1><p>The local API is temporarily unavailable. Please retry shortly.</p>" 503
    }}

    log {{
        output file "{_caddy_path(config.log_path)}" {{
            roll_size 10MiB
            roll_keep 5
            roll_keep_for 168h
        }}
        format filter {{
            wrap json
            fields {{
                request>headers delete
                request>uri delete
                resp_headers delete
            }}
        }}
    }}
}}
"""
