\set ON_ERROR_STOP on

SELECT format('CREATE ROLE cial_runtime LOGIN NOINHERIT PASSWORD %L', :'runtime_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cial_runtime')
\gexec
SELECT format('ALTER ROLE cial_runtime WITH LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD %L', :'runtime_password')
\gexec

GRANT CONNECT ON DATABASE cial_knowledge_os_dev TO cial_runtime;
GRANT USAGE ON SCHEMA public TO cial_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO cial_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO cial_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cial_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO cial_runtime;
