import { useEffect, useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { saveAnswerToKnowledge } from '@/api/client';
import type { ChatMessageData } from './ChatMessage';
import { toast } from 'sonner';

export default function SaveToKnowledgeDialog({message,suggestedTitle,onClose}:{message:ChatMessageData|null;suggestedTitle?:string|null;onClose:()=>void}){
  const[title,setTitle]=useState('');const[collection,setCollection]=useState('');const[tags,setTags]=useState('');const[description,setDescription]=useState('');const[citations,setCitations]=useState(true);const[question,setQuestion]=useState(true);const[context,setContext]=useState(false);const[saving,setSaving]=useState(false);
  useEffect(()=>{if(message){const firstLine=message.content.split('\n').find((line)=>line.trim())??'Saved AI answer';setTitle((suggestedTitle?.trim()||firstLine.replace(/^#+\s*/, '').replace(/[\*_`~]/g,'')).slice(0,120));}},[message,suggestedTitle]);
  const submit=async()=>{if(!message||!title.trim())return;setSaving(true);try{await saveAnswerToKnowledge({message_id:message.id,title:title.trim(),collection:collection.trim()||null,tags:tags.split(',').map((item)=>item.trim()).filter(Boolean),description:description.trim()||null,save_citations:citations,save_original_question:question,save_conversation_context:context});toast.success('Saved to Knowledge');onClose();}catch{toast.error('The answer could not be saved.');}finally{setSaving(false);}};
  return <Dialog open={Boolean(message)} onOpenChange={(open)=>{if(!open)onClose();}}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>Save to Knowledge</DialogTitle><DialogDescription>Preserve this grounded answer as a private, searchable knowledge asset.</DialogDescription></DialogHeader><div className="space-y-4 py-2"><label className="block text-sm font-medium">Title<input value={title} onChange={(event)=>setTitle(event.target.value)} maxLength={255} required className="mt-1 h-10 w-full rounded-lg border border-border px-3 font-normal outline-none focus:ring-2 focus:ring-primary"/></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Collection<input value={collection} onChange={(event)=>setCollection(event.target.value)} placeholder="Optional" className="mt-1 h-10 w-full rounded-lg border border-border px-3 font-normal"/></label><label className="text-sm font-medium">Tags<input value={tags} onChange={(event)=>setTags(event.target.value)} placeholder="Comma separated" className="mt-1 h-10 w-full rounded-lg border border-border px-3 font-normal"/></label></div><label className="block text-sm font-medium">Description<textarea value={description} onChange={(event)=>setDescription(event.target.value)} maxLength={2000} className="mt-1 min-h-20 w-full rounded-lg border border-border p-3 font-normal"/></label><fieldset className="space-y-2 text-sm"><legend className="mb-2 font-medium">Provenance</legend><label className="flex items-center gap-2"><input type="checkbox" checked={citations} onChange={(event)=>setCitations(event.target.checked)}/>Save citation snapshots and source links</label><label className="flex items-center gap-2"><input type="checkbox" checked={question} onChange={(event)=>setQuestion(event.target.checked)}/>Save original question</label><label className="flex items-center gap-2"><input type="checkbox" checked={context} onChange={(event)=>setContext(event.target.checked)}/>Save conversation context reference</label></fieldset></div><DialogFooter><Button variant="outline" onClick={onClose}>Cancel</Button><Button disabled={!title.trim()||saving} onClick={()=>void submit()}>{saving?'Saving…':'Save knowledge'}</Button></DialogFooter></DialogContent></Dialog>;
}
