import { useEffect, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Archive, Copy, Download, Lock, MoreHorizontal, Pin, Plus, Search, Trash2 } from 'lucide-react';
import { createMyNote, deleteMyNote, duplicateMyNote, getNoteExportUrl, listMyNotes, updateMyNote } from '@/api/client';
import type { WorkspaceNote, WorkspaceNoteList } from '@/data/workspace/workspaceTypes';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';

export default function NotesWorkspace({ createSignal = 0, initialNoteId = null }: { createSignal?: number; initialNoteId?: string | null }) {
  const client=useQueryClient(); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('all'); const [selectedId,setSelectedId]=useState<string|null>(null);
  const [draft,setDraft]=useState<WorkspaceNote|null>(null); const [saveState,setSaveState]=useState<'saved'|'saving'|'error'|'conflict'>('saved'); const textarea=useRef<HTMLTextAreaElement>(null); const lastSignal=useRef(createSignal);
  const notes=useQuery({queryKey:['notes',query,filter],queryFn:()=>listMyNotes({query,filter}),retry:false});
  const create=useMutation({mutationFn:()=>createMyNote(),onSuccess:(note)=>{client.setQueryData<WorkspaceNoteList>(['notes',query,filter],(old)=>old?{...old,items:[note,...old.items]}:{items:[note],next_cursor:null});setSelectedId(note.id);setDraft(note);requestAnimationFrame(()=>textarea.current?.focus());},onError:()=>toast.error('Could not create note')});
  useEffect(()=>{if(createSignal!==lastSignal.current){lastSignal.current=createSignal;create.mutate();}},[createSignal]);
  useEffect(()=>{const requested=selectedId??initialNoteId;const note=notes.data?.items.find((item)=>item.id===requested)??notes.data?.items[0]??null;setSelectedId(note?.id??null);setDraft(note);setSaveState('saved');},[notes.data,selectedId,initialNoteId]);
  useEffect(()=>{
    if(!draft)return; const server=notes.data?.items.find((item)=>item.id===draft.id); if(!server|| (server.title===draft.title&&server.content_markdown===draft.content_markdown))return;
    setSaveState('saving'); const timer=window.setTimeout(async()=>{try{const saved=await updateMyNote(draft.id,{expected_revision:server.revision,title:draft.title,content_markdown:draft.content_markdown,content_format:'markdown'});client.setQueryData(['notes',query,filter],(old:typeof notes.data)=>old?{...old,items:old.items.map((item)=>item.id===saved.id?saved:item)}:old);setDraft(saved);setSaveState('saved');}catch(error){const conflict=typeof error==='object'&&error!==null&&'status'in error&&(error as {status:number}).status===409;setSaveState(conflict?'conflict':'error');}},750); return()=>window.clearTimeout(timer);
  },[draft?.title,draft?.content_markdown]);
  useEffect(()=>{const save=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();textarea.current?.blur();}};window.addEventListener('keydown',save);return()=>window.removeEventListener('keydown',save);},[]);
  const patch=(value:Partial<WorkspaceNote>)=>setDraft((current)=>current?{...current,...value}:current);
  const mutateFlag=async(key:'is_pinned'|'is_archived')=>{if(!draft)return;try{const saved=await updateMyNote(draft.id,{expected_revision:draft.revision,[key]:!draft[key]});await client.invalidateQueries({queryKey:['notes']});setDraft(saved);}catch{toast.error('Note could not be updated');}};
  const remove=async()=>{if(!draft||!window.confirm(`Move “${draft.title}” to Trash?`))return;await deleteMyNote(draft.id);setSelectedId(null);setDraft(null);await client.invalidateQueries({queryKey:['notes']});};
  const duplicate=async()=>{if(!draft)return;const copy=await duplicateMyNote(draft.id);await client.invalidateQueries({queryKey:['notes']});setSelectedId(copy.id);};
  return <section className="grid min-h-[34rem] overflow-hidden rounded-2xl border border-slate-200 bg-white md:grid-cols-[minmax(16rem,30%)_1fr]" data-testid="notes-workspace">
    <aside className={cn('border-r border-slate-200',draft&&'hidden md:block')}>
      <div className="space-y-3 border-b border-slate-200 p-3"><label className="relative block"><Search size={15} className="absolute left-3 top-2.5 text-slate-400"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search notes" className="h-9 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"/></label><div className="flex gap-1 overflow-x-auto">{['all','pinned','recent','archived','trash'].map((item)=><button key={item} onClick={()=>setFilter(item)} className={cn('rounded-md px-2.5 py-1.5 text-xs capitalize',filter===item?'bg-[#eaf3e5] font-semibold text-primary':'text-slate-600 hover:bg-slate-100')}>{item}</button>)}</div><Button size="sm" className="w-full" onClick={()=>create.mutate()} disabled={create.isPending}><Plus size={15}/>New note</Button></div>
      {notes.isLoading?<p className="p-5 text-sm text-slate-500">Loading notes…</p>:notes.isError?<div className="p-5 text-sm text-red-700">Notes could not be loaded. <button className="underline" onClick={()=>notes.refetch()}>Retry</button></div>:notes.data?.items.length? <div>{notes.data.items.map((note)=><button key={note.id} onClick={()=>setSelectedId(note.id)} className={cn('w-full border-b border-slate-100 px-4 py-3 text-left hover:bg-[#fafcf9]',selectedId===note.id&&'bg-[#edf5e9]')}><div className="flex items-center gap-2"><strong className="min-w-0 flex-1 truncate text-sm text-slate-900">{note.title}</strong>{note.is_pinned?<Pin size={13} className="text-primary"/>:null}</div><p className="mt-1 truncate text-xs text-slate-500">{note.plain_text||'Empty note'}</p><p className="mt-2 text-[11px] text-slate-400">{new Date(note.updated_at).toLocaleString()}</p></button>)}</div>:<div className="p-8 text-center"><p className="text-sm font-semibold">No notes yet</p><p className="mt-1 text-xs text-slate-500">Create a private note to get started.</p><Button size="sm" className="mt-4" onClick={()=>create.mutate()}><Plus size={15}/>Create note</Button></div>}
    </aside>
    <div className={cn('min-w-0',!draft&&'hidden md:block')}>{draft?<><header className="flex flex-wrap items-center gap-2 border-b border-slate-200 px-4 py-3"><button className="mr-1 text-sm text-primary md:hidden" onClick={()=>setDraft(null)}>Back</button><input value={draft.title} onChange={(e)=>patch({title:e.target.value})} aria-label="Note title" className="min-w-40 flex-1 bg-transparent text-xl font-semibold outline-none focus-visible:ring-2 focus-visible:ring-primary"/><span className="inline-flex items-center gap-1 text-xs text-slate-500"><Lock size={12}/>Private</span><span className={cn('text-xs',saveState==='error'||saveState==='conflict'?'text-red-700':'text-slate-500')}>{saveState==='saving'?'Saving…':saveState==='saved'?'Saved':saveState==='conflict'?'Editing conflict — reload to resolve':'Save failed — changes retained'}</span><Button variant="ghost" size="icon" aria-label={draft.is_pinned?'Unpin note':'Pin note'} onClick={()=>void mutateFlag('is_pinned')}><Pin size={16} fill={draft.is_pinned?'currentColor':'none'}/></Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label="Note actions"><MoreHorizontal size={17}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={()=>void duplicate()}><Copy/>Duplicate</DropdownMenuItem><DropdownMenuItem asChild><a href={getNoteExportUrl(draft.id)}><Download/>Export Markdown</a></DropdownMenuItem><DropdownMenuItem onSelect={()=>void mutateFlag('is_archived')}><Archive/>{draft.is_archived?'Unarchive':'Archive'}</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem className="text-red-700" onSelect={()=>void remove()}><Trash2/>Move to Trash</DropdownMenuItem></DropdownMenuContent></DropdownMenu></header><div className="p-4 sm:p-6"><textarea ref={textarea} value={draft.content_markdown} onChange={(e)=>patch({content_markdown:e.target.value})} aria-label="Note content" placeholder="Start writing… Markdown formatting is supported." className="min-h-[26rem] w-full resize-none bg-transparent text-[15px] leading-7 text-slate-800 outline-none focus-visible:ring-2 focus-visible:ring-primary"/></div><footer className="border-t border-slate-200 px-5 py-3 text-xs text-slate-500">{draft.linked_documents.length} linked documents · Revision {draft.revision}</footer></>:<div className="flex min-h-[34rem] items-center justify-center text-sm text-slate-500">Select or create a note.</div>}</div>
  </section>;
}
