import { useEffect, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Archive, Bot, Copy, Download, Link2, Lock, MoreHorizontal, Pin, Plus, Search, ShieldCheck, Tag, Trash2, X } from 'lucide-react';
import { useLocation } from 'wouter';
import { addNoteTag, createMyNote, createNoteTag, deleteMyNote, deleteNoteTag, duplicateMyNote, getCorpusTree, getMyWorkspaceFolder, getNoteExportUrl, linkNoteDocument, listMyNotes, listNoteTags, removeNoteTag, renameNoteTag, unlinkNoteDocument, updateMyNote } from '@/api/client';
import { flattenCorpusTree } from '@/api/adapters';
import type { WorkspaceNote, WorkspaceNoteList } from '@/data/workspace/workspaceTypes';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';
import RichNoteEditor from './RichNoteEditor';

export default function NotesWorkspace({ createSignal = 0, initialNoteId = null }: { createSignal?: number; initialNoteId?: string | null }) {
  const client = useQueryClient(); const [, setLocation] = useLocation(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [tagFilter,setTagFilter]=useState<string|null>(null); const [selectedId, setSelectedId] = useState<string | null>(null);
  const [draft, setDraft] = useState<WorkspaceNote | null>(null); const [saveState, setSaveState] = useState<'saved' | 'saving' | 'error' | 'conflict'>('saved'); const [saveDelay,setSaveDelay]=useState(750); const lastSignal = useRef(createSignal);
  const notes = useQuery({ queryKey: ['notes', query, filter,tagFilter], queryFn: () => listMyNotes({ query, filter,tagId:tagFilter }), retry: false });
  const tags=useQuery({queryKey:['note-tags'],queryFn:listNoteTags,retry:false});
  const personalDocuments=useQuery({queryKey:['note-link-personal-documents'],queryFn:()=>getMyWorkspaceFolder(null),retry:false});
  const enterpriseDocuments=useQuery({queryKey:['note-link-enterprise-documents'],queryFn:getCorpusTree,retry:false});
  const create = useMutation({ mutationFn: () => createMyNote(), onSuccess: (note) => { client.setQueryData<WorkspaceNoteList>(['notes', query, filter], (old) => old ? { ...old, items: [note, ...old.items] } : { items: [note], next_cursor: null }); setSelectedId(note.id); setDraft(note); }, onError: () => toast.error('Could not create note') });
  useEffect(() => { if (createSignal !== lastSignal.current) { lastSignal.current = createSignal; create.mutate(); } }, [createSignal]);
  useEffect(() => { const requested = selectedId ?? initialNoteId; const note = notes.data?.items.find((item) => item.id === requested) ?? notes.data?.items[0] ?? null; setSelectedId(note?.id ?? null); setDraft(note); setSaveState('saved'); }, [notes.data, selectedId, initialNoteId]);
  useEffect(() => {
    if (!draft) return; const server = notes.data?.items.find((item) => item.id === draft.id); if (!server || (server.title === draft.title && server.content_markdown === draft.content_markdown && JSON.stringify(server.content_json)===JSON.stringify(draft.content_json))) {if(saveDelay===0)queueMicrotask(()=>setSaveDelay(750));return;}
    setSaveState('saving'); const timer = window.setTimeout(async () => { try { const saved = await updateMyNote(draft.id, { expected_revision: server.revision, title: draft.title, content_json: draft.content_json, content_markdown: draft.content_markdown, content_format: 'editor_json' }); client.setQueryData(['notes', query, filter], (old: typeof notes.data) => old ? { ...old, items: old.items.map((item) => item.id === saved.id ? saved : item) } : old); setDraft(saved); setSaveState('saved'); } catch (error) { const conflict = typeof error === 'object' && error !== null && 'status' in error && (error as { status: number }).status === 409; setSaveState(conflict ? 'conflict' : 'error'); } finally {setSaveDelay(750);} }, saveDelay); return () => window.clearTimeout(timer);
  }, [draft?.title, draft?.content_markdown, draft?.content_json,saveDelay]);
  useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();setSaveDelay(0);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
  const patch = (value: Partial<WorkspaceNote>) => setDraft((current) => current ? { ...current, ...value } : current);
  const mutateFlag = async (key: 'is_pinned' | 'is_archived') => { if (!draft) return; try { const saved = await updateMyNote(draft.id, { expected_revision: draft.revision, [key]: !draft[key] }); await client.invalidateQueries({ queryKey: ['notes'] }); setDraft(saved); } catch { toast.error('Note could not be updated'); } };
  const remove = async () => { if (!draft || !window.confirm(`Move “${draft.title}” to Trash?`)) return; await deleteMyNote(draft.id); setSelectedId(null); setDraft(null); await client.invalidateQueries({ queryKey: ['notes'] }); };
  const duplicate = async () => { if (!draft) return; const copy = await duplicateMyNote(draft.id); await client.invalidateQueries({ queryKey: ['notes'] }); setSelectedId(copy.id); };
  const useInAssistant = (navigate: boolean) => { if (!draft || draft.indexing_status !== 'indexed' || draft.indexed_revision !== draft.revision) { toast.info('Wait for this note to finish indexing before using it with AI.'); return; } const context = { id: draft.id, type: 'note', title: draft.title, relative_path: `notes/${draft.id}`, updated_at: draft.updated_at, is_pinned: draft.is_pinned }; window.localStorage.setItem('cial-assistant-selected-context', JSON.stringify([context])); window.localStorage.setItem('cial-assistant-context-intent', String(Date.now())); toast.success('Note added to AI context'); if (navigate) setLocation('/assistant'); };
  const createAndAddTag=async()=>{if(!draft)return;const name=window.prompt('Tag name');if(!name?.trim())return;try{const tag=await createNoteTag(name.trim());const saved=await addNoteTag(draft.id,tag.id);setDraft(saved);await Promise.all([client.invalidateQueries({queryKey:['notes']}),client.invalidateQueries({queryKey:['note-tags']})]);}catch{toast.error('Tag could not be added');}};
  const manageTags=async()=>{const current=tags.data?.items??[];const selected=window.prompt(`Enter the exact tag to rename or delete:\n${current.map((tag)=>tag.name).join('\n')}`);const tag=current.find((item)=>item.name.localeCompare(selected??'',undefined,{sensitivity:'accent'})===0);if(!tag)return;const next=window.prompt('New tag name (leave empty to delete)',tag.name);try{if(next?.trim())await renameNoteTag(tag.id,next.trim(),tag.color??undefined);else if(next!==null&&window.confirm(`Delete tag “${tag.name}”?`))await deleteNoteTag(tag.id);await Promise.all([client.invalidateQueries({queryKey:['note-tags']}),client.invalidateQueries({queryKey:['notes']})]);}catch{toast.error('Tag could not be updated');}};
  const toggleTag=async(tag:{id:string;name:string})=>{if(!draft)return;try{const applied=draft.tags.some((item)=>item.id===tag.id);if(applied){await removeNoteTag(draft.id,tag.id);setDraft({...draft,tags:draft.tags.filter((item)=>item.id!==tag.id)});}else setDraft(await addNoteTag(draft.id,tag.id));await client.invalidateQueries({queryKey:['notes']});}catch{toast.error('Tag could not be updated');}};
  const unlinkDocument=async(documentId:string)=>{if(!draft)return;try{await unlinkNoteDocument(draft.id,documentId);setDraft({...draft,linked_documents:draft.linked_documents.filter((item)=>item.id!==documentId)});await client.invalidateQueries({queryKey:['notes']});}catch{toast.error('Document could not be unlinked');}};
  const linkDocument=async()=>{if(!draft)return;const documents=[...(personalDocuments.data?.documents??[]),...(enterpriseDocuments.data?flattenCorpusTree(enterpriseDocuments.data.root).documents:[])];const name=window.prompt(`Link a document by exact name:\n${documents.slice(0,20).map((item)=>item.name).join('\n')}`);if(!name?.trim())return;const document=documents.find((item)=>item.name.localeCompare(name.trim(),undefined,{sensitivity:'accent'})===0);if(!document){toast.error('No authorized document matched that name');return;}try{const saved=await linkNoteDocument(draft.id,document.id);setDraft(saved);await client.invalidateQueries({queryKey:['notes']});}catch{toast.error('Document could not be linked');}};
  const citation = new URLSearchParams(window.location.search).get('citation');

  return <section className="grid min-h-[34rem] overflow-hidden rounded-2xl border border-slate-200 bg-white md:grid-cols-[minmax(16rem,30%)_1fr]" data-testid="notes-workspace">
    <aside className={cn('border-r border-slate-200', draft && 'hidden md:block')}>
      <div className="space-y-3 border-b border-slate-200 p-3"><label className="relative block"><Search size={15} className="absolute left-3 top-2.5 text-slate-400"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search notes" className="h-9 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"/></label><div className="flex gap-1 overflow-x-auto">{['all', 'pinned', 'recent', 'archived', 'trash'].map((item) => <button key={item} onClick={() => setFilter(item)} className={cn('rounded-md px-2.5 py-1.5 text-xs capitalize', filter === item ? 'bg-[#eaf3e5] font-semibold text-primary' : 'text-slate-600 hover:bg-slate-100')}>{item}</button>)}</div><Button size="sm" className="w-full" onClick={() => create.mutate()} disabled={create.isPending}><Plus size={15}/>New note</Button></div>
      {notes.isLoading ? <p className="p-5 text-sm text-slate-500">Loading notes…</p> : notes.isError ? <div className="p-5 text-sm text-red-700">Notes could not be loaded. <button className="underline" onClick={() => notes.refetch()}>Retry</button></div> : notes.data?.items.length ? <div>{notes.data.items.map((note) => <button key={note.id} onClick={() => setSelectedId(note.id)} className={cn('w-full border-b border-slate-100 px-4 py-3 text-left hover:bg-[#fafcf9]', selectedId === note.id && 'bg-[#edf5e9]')}><div className="flex items-center gap-2"><strong className="min-w-0 flex-1 truncate text-sm text-slate-900">{note.title}</strong>{note.is_pinned ? <Pin size={13} className="text-primary"/> : null}</div><p className="mt-1 truncate text-xs text-slate-500">{note.plain_text || 'Empty note'}</p><p className="mt-2 text-[11px] text-slate-400">{new Date(note.updated_at).toLocaleString()}</p></button>)}</div> : <div className="p-8 text-center"><p className="text-sm font-semibold">No notes yet</p><p className="mt-1 text-xs text-slate-500">Create a private note to get started.</p><Button size="sm" className="mt-4" onClick={() => create.mutate()}><Plus size={15}/>Create note</Button></div>}
      <div className="border-t border-slate-200 p-3"><div className="mb-2 flex items-center justify-between"><span className="flex items-center gap-1 text-xs font-semibold"><Tag size={13}/>Tags</span>{draft?<button onClick={()=>void createAndAddTag()} className="text-xs text-primary">Create</button>:null}</div><div className="flex flex-wrap gap-1"><button onClick={()=>setTagFilter(null)} className={cn('rounded px-2 py-1 text-[11px]',!tagFilter?'bg-[#eaf3e5] text-primary':'bg-slate-100')}>All</button>{tags.data?.items.map((tag)=><button key={tag.id} onClick={()=>draft?void toggleTag(tag):setTagFilter(tag.id)} onDoubleClick={()=>setTagFilter(tag.id)} className={cn('rounded px-2 py-1 text-[11px]',tagFilter===tag.id||draft?.tags.some((item)=>item.id===tag.id)?'bg-[#eaf3e5] text-primary':'bg-slate-100')}>{tag.name}</button>)}</div>{draft?.linked_documents.length?<div className="mt-3 border-t border-slate-100 pt-3"><p className="mb-1 flex items-center gap-1 text-xs font-semibold"><Link2 size={13}/>Linked documents ({draft.linked_documents.length})</p>{draft.linked_documents.map((document)=><div key={document.id} className="flex items-center gap-1 py-1 text-xs"><a className="min-w-0 flex-1 truncate text-primary hover:underline" href={`/knowledge/document/${document.id}`}>{document.name}</a><span className="text-[10px] uppercase text-slate-400">{document.scope||document.file_type}</span><button aria-label={`Unlink ${document.name}`} onClick={()=>void unlinkDocument(document.id)} className="rounded p-1 hover:bg-slate-100"><X size={12}/></button></div>)}</div>:null}</div>
      <div className="m-3 mt-0 flex gap-2"><button className="flex flex-1 items-center justify-center gap-1 rounded-md border border-slate-200 px-2 py-1.5 text-xs text-primary hover:bg-[#f1f6ee]" onClick={()=>void manageTags()}><Tag size={13}/>Manage tags</button>{draft?<button className="flex flex-1 items-center justify-center gap-1 rounded-md border border-slate-200 px-2 py-1.5 text-xs text-primary hover:bg-[#f1f6ee]" onClick={()=>void linkDocument()}><Link2 size={13}/>Link document</button>:null}</div>
    </aside>
    <div className={cn('min-w-0', !draft && 'hidden md:block')}>{draft ? <><header className="flex flex-wrap items-center gap-2 border-b border-slate-200 px-4 py-3"><button className="mr-1 text-sm text-primary md:hidden" onClick={() => setDraft(null)}>Back</button><input value={draft.title} onChange={(event) => patch({ title: event.target.value })} aria-label="Note title" className="min-w-40 flex-1 bg-transparent text-xl font-semibold outline-none focus-visible:ring-2 focus-visible:ring-primary"/><span className="inline-flex items-center gap-1 text-xs text-slate-500"><Lock size={12}/>Private</span><span className={cn('text-xs', saveState === 'error' || saveState === 'conflict' ? 'text-red-700' : 'text-slate-500')}>{saveState === 'saving' ? 'Saving…' : saveState === 'saved' ? 'Saved' : saveState === 'conflict' ? 'Editing conflict — reload to resolve' : 'Save failed — changes retained'}</span><Button variant="ghost" size="sm" onClick={() => useInAssistant(false)} disabled={draft.indexing_status !== 'indexed'} title={draft.indexing_status === 'indexed' ? 'Add this note to the assistant context' : `Indexing: ${draft.indexing_status}`}><ShieldCheck size={15}/>Add to AI context</Button><Button variant="ghost" size="sm" onClick={() => useInAssistant(true)} disabled={draft.indexing_status !== 'indexed'}><Bot size={15}/>Ask AI</Button><Button variant="ghost" size="icon" aria-label={draft.is_pinned ? 'Unpin note' : 'Pin note'} onClick={() => void mutateFlag('is_pinned')}><Pin size={16} fill={draft.is_pinned ? 'currentColor' : 'none'}/></Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label="Note actions"><MoreHorizontal size={17}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => void duplicate()}><Copy/>Duplicate</DropdownMenuItem><DropdownMenuItem asChild><a href={getNoteExportUrl(draft.id)}><Download/>Export Markdown</a></DropdownMenuItem><DropdownMenuItem onSelect={() => void mutateFlag('is_archived')}><Archive/>{draft.is_archived ? 'Unarchive' : 'Archive'}</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem className="text-red-700" onSelect={() => void remove()}><Trash2/>Move to Trash</DropdownMenuItem></DropdownMenuContent></DropdownMenu></header><div className="p-4 sm:p-6"><RichNoteEditor noteId={draft.id} contentJson={draft.content_json} markdown={draft.content_markdown} citationBlockId={citation} onChange={(value) => patch(value)}/></div><footer className="border-t border-slate-200 px-5 py-3 text-xs text-slate-500">{draft.linked_documents.length} linked documents · Revision {draft.revision} · {draft.indexing_status === 'indexed' ? 'AI index ready' : `AI index ${draft.indexing_status}`}</footer></> : <div className="flex min-h-[34rem] items-center justify-center text-sm text-slate-500">Select or create a note.</div>}</div>
  </section>;
}
