import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from 'react';
import { useLocation } from 'wouter';
import { Bot, ChevronRight, Clock3, FileText, Filter, FolderOpen, MessageSquare, NotebookPen, Search, Settings, Sparkles, StickyNote, Upload, X } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { clearRecentSearches, globalSearch, listRecentSearches } from '@/api/client';
import type { GlobalSearchFilters, GlobalSearchResult, GlobalSearchType, RecentSearchList } from '@/api/types';
import { createConversationHandoff } from '@/lib/conversationHandoff';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';

interface PaletteContext { open:boolean; setOpen:(value:boolean)=>void; }
const CommandPaletteContext=createContext<PaletteContext|null>(null);
export function useCommandPalette(){const value=useContext(CommandPaletteContext);if(!value)throw new Error('useCommandPalette must be used within CommandPaletteProvider');return value;}
export function CommandPaletteProvider({children}:{children:React.ReactNode}){const[open,setOpen]=useState(false);useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setOpen((value)=>!value);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);return <CommandPaletteContext.Provider value={{open,setOpen}}>{children}</CommandPaletteContext.Provider>;}

const emptyFilters:GlobalSearchFilters={types:[],scope:'all_accessible',file_types:[],department_ids:[],workspace_ids:[]};
const typeLabels:Record<GlobalSearchType,string>={document:'Documents',passage:'Passages',note:'Notes',conversation:'Conversations',summary:'Summaries',saved_knowledge:'Saved Knowledge',folder:'Folders'};
const searchableTypes=(Object.keys(typeLabels) as GlobalSearchType[]).filter((item)=>item!=='folder');
const iconFor=(type:GlobalSearchType)=>type==='document'?FileText:type==='passage'?NotebookPen:type==='note'?StickyNote:type==='conversation'?MessageSquare:type==='folder'?FolderOpen:Sparkles;

export function CommandPalette(){
  const{open,setOpen}=useCommandPalette();const[,navigate]=useLocation();const[query,setQuery]=useState('');const[results,setResults]=useState<GlobalSearchResult[]>([]);const[counts,setCounts]=useState<Record<string,number>>({});const[recent,setRecent]=useState<RecentSearchList['items']>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);const[filters,setFilters]=useState<GlobalSearchFilters>(emptyFilters);const[filtersOpen,setFiltersOpen]=useState(false);const[activeType,setActiveType]=useState<'all'|GlobalSearchType>('all');const[selected,setSelected]=useState(new Set<string>());const[activeIndex,setActiveIndex]=useState(0);const[interpretation,setInterpretation]=useState<{applied:boolean;explanation:string|null;chips:string[]}>({applied:false,explanation:null,chips:[]});const request=useRef(0);const keyboardResultMode=useRef(false);
  const visible=useMemo(()=>activeType==='all'?results:results.filter((item)=>item.type===activeType),[activeType,results]);
  const filterCount=filters.types.length+filters.file_types.length+(filters.scope==='all_accessible'?0:1)+(filters.updated_after?1:0);
  useEffect(()=>{if(!open)return;setQuery('');setResults([]);setError(null);setSelected(new Set());void listRecentSearches().then((value)=>setRecent(value.items)).catch(()=>setRecent([]));},[open]);
  useEffect(()=>{if(!open||!query.trim()){setResults([]);setLoading(false);return;}const generation=++request.current;const controller=new AbortController();setLoading(true);setError(null);const timer=window.setTimeout(()=>{void globalSearch({query:query.trim(),mode:query.trim().length<3?'instant':'full',filters,limit:40,interpret:true},controller.signal).then((value)=>{if(generation!==request.current)return;setResults(value.items);setCounts(value.counts);setInterpretation(value.interpretation);setActiveIndex(0);}).catch((cause)=>{if(generation===request.current&&cause?.name!=='AbortError')setError('Search is temporarily unavailable.');}).finally(()=>{if(generation===request.current)setLoading(false);});},query.trim().length<3?150:350);return()=>{window.clearTimeout(timer);controller.abort();};},[open,query,filters]);
  const openResult=useCallback((item:GlobalSearchResult,newTab=false)=>{setOpen(false);if(newTab)window.open(item.deep_link,'_blank','noopener,noreferrer');else navigate(item.deep_link);},[navigate,setOpen]);
  const askAI=useCallback(async()=>{const chosen=results.filter((item)=>selected.has(`${item.type}:${item.id}`));const documents=[...new Set(chosen.map((item)=>item.document_id).filter((value):value is string=>Boolean(value)))];const notes=chosen.filter((item)=>item.type==='note').map((item)=>item.id);try{const session=await createConversationHandoff({title:query.trim()||'New conversation',origin:'global_search',context_scope:documents.length||notes.length?'selected_context':'all_accessible',selected_document_ids:documents,selected_note_ids:notes,question:query.trim()||undefined,contextItems:chosen.filter((item)=>item.can_use_as_context).map((item)=>({id:item.document_id??item.id,type:item.type==='note'?'note':'document',title:item.title,relative_path:item.deep_link,file_type:item.file_type??undefined}))});setOpen(false);navigate(`/assistant?session=${session.id}`);}catch{toast.error('A new authorized conversation could not be created.');}},[navigate,query,results,selected,setOpen]);
  useEffect(()=>{if(!open)return;const handler=(event:KeyboardEvent)=>{if(event.key==='ArrowDown'){event.preventDefault();keyboardResultMode.current=true;setActiveIndex((value)=>Math.min(value+1,visible.length-1));}else if(event.key==='ArrowUp'){event.preventDefault();keyboardResultMode.current=true;setActiveIndex((value)=>Math.max(value-1,0));}else if(event.key==='Enter'&&visible[activeIndex]){event.preventDefault();openResult(visible[activeIndex],event.ctrlKey||event.metaKey);}else if(event.code==='Space'&&keyboardResultMode.current&&visible[activeIndex]?.can_use_as_context){event.preventDefault();const key=`${visible[activeIndex].type}:${visible[activeIndex].id}`;setSelected((current)=>{const next=new Set(current);next.has(key)?next.delete(key):next.add(key);return next;});}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[activeIndex,open,openResult,visible]);
  const quick=[{title:'Ask AI',detail:'Ask questions with grounded sources',icon:Sparkles,run:()=>void askAI()},{title:'Upload file',detail:'Add documents to your workspace',icon:Upload,run:()=>{setOpen(false);navigate('/workspace/documents');}},{title:'New note',detail:'Create a private note',icon:StickyNote,run:()=>{setOpen(false);navigate('/workspace/notes?new=1');}},{title:'New conversation',detail:'Start a clean assistant session',icon:MessageSquare,run:()=>void askAI()}];
  const navigation=[{title:'Knowledge Center',detail:'Browse manuals and SOPs',icon:FolderOpen,path:'/knowledge-center'},{title:'My Workspace',detail:'Access private workspace',icon:NotebookPen,path:'/workspace'},{title:'Settings',detail:'Configure preferences',icon:Settings,path:'/admin'}];
  const toggleType=(type:GlobalSearchType)=>setFilters((current)=>({...current,types:current.types.includes(type)?current.types.filter((item)=>item!==type):[...current.types,type]}));
  return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="top-[8vh] w-[calc(100vw-1rem)] max-w-[46rem] translate-y-0 overflow-hidden rounded-2xl border-slate-200 p-0 shadow-2xl sm:top-[12vh] [&>button]:hidden"><DialogTitle className="sr-only">Global search</DialogTitle><DialogDescription className="sr-only">Search authorized documents, passages, notes, conversations, summaries, and actions.</DialogDescription>
    <div className="flex h-14 items-center gap-3 border-b border-slate-200 px-4"><Search size={18} className="text-slate-400"/><input autoFocus value={query} onChange={(event)=>{keyboardResultMode.current=false;setQuery(event.target.value);}} placeholder="Search documents, notes, conversations, and actions…" aria-label="Global search" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-slate-400"/>{loading?<span className="h-4 w-4 animate-spin rounded-full border-2 border-primary border-t-transparent" aria-label="Searching"/>:query?<button onClick={()=>setQuery('')} aria-label="Clear search"><X size={16}/></button>:null}</div>
    {query?<><div className="flex items-center gap-1 overflow-x-auto border-b border-slate-100 px-3 py-2 text-xs"><button onClick={()=>setActiveType('all')} className={cn('rounded-lg px-3 py-1.5',activeType==='all'?'bg-[#eaf3e5] font-semibold text-primary':'text-slate-600')}>All</button>{searchableTypes.map((type)=><button key={type} onClick={()=>setActiveType(type)} className={cn('rounded-lg px-3 py-1.5 whitespace-nowrap',activeType===type?'bg-[#eaf3e5] font-semibold text-primary':'text-slate-600')}>{typeLabels[type]}{counts[type]?` ${counts[type]}`:''}</button>)}<button onClick={()=>setFiltersOpen((value)=>!value)} className="ml-auto inline-flex items-center gap-1 rounded-lg bg-slate-100 px-3 py-1.5"><Filter size={13}/>Filters{filterCount?` ${filterCount}`:''}</button></div>
      {filtersOpen?<div className="grid gap-4 border-b border-slate-200 bg-[#fbfcfa] p-4 text-xs sm:grid-cols-3"><fieldset><legend className="mb-2 font-semibold">Type</legend>{searchableTypes.map((type)=><label key={type} className="flex items-center gap-2 py-1"><input type="checkbox" checked={filters.types.includes(type)} onChange={()=>toggleType(type)}/>{typeLabels[type]}</label>)}</fieldset><fieldset><legend className="mb-2 font-semibold">Scope</legend>{(['all_accessible','enterprise','my_workspace'] as const).map((scope)=><label key={scope} className="flex items-center gap-2 py-1"><input type="radio" checked={filters.scope===scope} onChange={()=>setFilters((value)=>({...value,scope}))}/>{scope==='all_accessible'?'All accessible':scope==='enterprise'?'Enterprise':'My Workspace'}</label>)}</fieldset><fieldset><legend className="mb-2 font-semibold">File type</legend>{['PDF','DOCX','PPTX','XLSX','Other'].map((type)=><label key={type} className="flex items-center gap-2 py-1"><input type="checkbox" checked={filters.file_types.includes(type)} onChange={()=>setFilters((value)=>({...value,file_types:value.file_types.includes(type)?value.file_types.filter((item)=>item!==type):[...value.file_types,type]}))}/>{type}</label>)}<button onClick={()=>setFilters(emptyFilters)} className="mt-2 text-primary">Clear all filters</button></fieldset></div>:null}
      {interpretation.applied?<div className="flex flex-wrap items-center gap-2 border-b border-slate-100 bg-[#f5f8f3] px-4 py-2 text-xs"><span className="font-semibold">Interpreted as:</span>{interpretation.chips.map((chip)=><span key={chip} className="rounded-full bg-white px-2 py-1">{chip}</span>)}<button onClick={()=>setInterpretation({applied:false,explanation:null,chips:[]})} className="ml-auto text-primary">Undo interpretation</button></div>:null}
      <div className="max-h-[52vh] min-h-64 overflow-y-auto p-2" role="listbox">{error?<div className="p-8 text-center text-sm text-red-700">{error}<button className="ml-2 underline" onClick={()=>setFilters({...filters})}>Retry</button></div>:visible.length?visible.map((item,index)=>{const Icon=iconFor(item.type);const key=`${item.type}:${item.id}`;return <button key={key} role="option" aria-selected={index===activeIndex} onMouseEnter={()=>setActiveIndex(index)} onClick={()=>openResult(item)} className={cn('flex w-full items-start gap-3 rounded-xl px-3 py-3 text-left transition',index===activeIndex?'bg-[#eaf3e5]':'hover:bg-slate-50')}><span className="mt-0.5 rounded-lg bg-white p-2 text-primary"><Icon size={16}/></span><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><strong className="truncate text-sm">{item.title}</strong><span className="ml-auto text-[11px] font-semibold text-primary">{item.relevance}</span></span><span className="mt-1 block text-[11px] text-slate-500">{typeLabels[item.type]}{item.workspace?` · ${item.workspace}`:''}{item.page?` · Page ${item.page}`:''}{item.file_type?` · ${item.file_type}`:''}</span>{item.excerpt?<span className="mt-1 line-clamp-2 block text-xs leading-5 text-slate-600">{item.excerpt}</span>:null}<span className="mt-1 block text-[11px] text-slate-500">{item.match_reasons.join(' · ')}</span></span>{item.can_use_as_context?<span onClick={(event)=>{event.stopPropagation();setSelected((current)=>{const next=new Set(current);next.has(key)?next.delete(key):next.add(key);return next;});}} className={cn('mt-1 h-4 w-4 rounded border',selected.has(key)?'border-primary bg-primary':'border-slate-300')} aria-label={`Select ${item.title} as AI context`}/>:null}</button>}):!loading?<div className="p-10 text-center text-sm text-slate-500">No accessible results. Try a different phrase or clear filters.</div>:null}</div>
      <div className="px-3 pb-3"><button onClick={()=>void askAI()} className="flex w-full items-center gap-3 rounded-xl border border-[#cfdec9] bg-[#f1f6ee] px-4 py-3 text-left text-sm font-semibold text-primary"><Sparkles size={17}/>{selected.size?`Ask AI using ${selected.size} selected results`:`Ask AI about “${query.trim()}”`}<ChevronRight size={16} className="ml-auto"/></button></div></>:<div className="max-h-[62vh] overflow-y-auto p-3"><section><div className="mb-2 flex items-center justify-between px-2"><h3 className="text-xs font-semibold text-slate-500">Recent searches</h3>{recent.length?<button className="text-xs text-primary" onClick={()=>void clearRecentSearches().then(()=>setRecent([]))}>Clear</button>:null}</div>{recent.length?recent.map((item)=><button key={item.id} onClick={()=>setQuery(item.query)} className="flex w-full items-center gap-3 rounded-lg px-2 py-2 text-left text-sm hover:bg-slate-50"><Clock3 size={15} className="text-slate-400"/>{item.query}</button>):<p className="px-2 py-3 text-xs text-slate-400">Your recent searches will appear here.</p>}</section><section className="mt-3 border-t border-slate-100 pt-3"><h3 className="mb-2 px-2 text-xs font-semibold text-slate-500">Quick actions</h3>{quick.map((item)=><button key={item.title} onClick={item.run} className="flex w-full items-center gap-3 rounded-lg px-2 py-2 text-left hover:bg-slate-50"><item.icon size={16} className={item.title==='Ask AI'?'text-primary':'text-slate-500'}/><span><strong className="block text-sm">{item.title}</strong><span className="text-xs text-slate-500">{item.detail}</span></span></button>)}</section><section className="mt-3 border-t border-slate-100 pt-3"><h3 className="mb-2 px-2 text-xs font-semibold text-slate-500">Navigate</h3>{navigation.map((item)=><button key={item.title} onClick={()=>{setOpen(false);navigate(item.path);}} className="flex w-full items-center gap-3 rounded-lg px-2 py-2 text-left hover:bg-slate-50"><item.icon size={16} className="text-slate-500"/><span><strong className="block text-sm">{item.title}</strong><span className="text-xs text-slate-500">{item.detail}</span></span></button>)}</section></div>}
    <footer className="flex h-10 items-center gap-4 border-t border-slate-200 px-4 text-[11px] text-slate-500"><span>↑↓ Navigate</span><span>Enter Open</span><span>Ctrl+Enter New tab</span><span>Space Select</span><span className="ml-auto">Esc Close</span></footer>
  </DialogContent></Dialog>;
}
