export const THEME = {
  primaryGreen: '#4a7c3f',
  darkOlive: '#2d4f22',
  lightGreen: '#7ab648',
  softMint: '#f3f6f1',
  accentOrange: '#e8820c',
  background: '#f6f7f9',
  cardBackground: '#ffffff',
  borderColor: '#dfe3e8',
  textPrimary: '#171d26',
  textSecondary: '#5f6b7a',
  danger: '#c0392b',
  warning: '#e67e22',
  success: '#27ae60',
  logoPath: '/cial-logo.png',
  appName: 'CIAL Knowledge OS',
  tagline: 'Your intelligent knowledge platform',
  departmentName: 'Engineering Dept.',
  footerText: 'Copyright 2026 Cochin International Airport Limited (CIAL). All rights reserved.',
  heroBackground: 'hsl(210 20% 98%)',
  sidebarBottomBackground: 'hsl(216 24% 12%)',
  swagathamText: 'Swagatham to greener skies',
};
